
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React, {ReactNode} from "react";
import Home from "@/app/page";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,


}: Readonly<{
  children: React.ReactNode;


}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
      {/*<h4 className={'flex text-5xl p-10 font-bold  items-center justify-center'}>Welcome , to the E-commerce Kingdom!!</h4>*/}
         {children}
      </body>
    </html>
  );
}
